@HOST = http://localhost:4050/api
@API_KEY = cfrw9D3kOE9RT6yG
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjNDQ4NGZlMS1mYTVlLTQzMTUtOWUwYi02MGEyOWU0ODFlYzciLCJpYXQiOjE3NTM0NTc2NTgsImV4cCI6MTc1MzQ3NTY1OH0.9HHggp2W3_Xat8cfs-Lz-_hAliYcfLUw_4e6JTfi8tM



POST {{HOST}}/kiu/availability-flights
Content-Type: application/json
x-api-key: {{API_KEY}}
Authorization: Bearer {{TOKEN}}

{
  "adults":1,
  "children":0,
  "infants":0,
  "origin":"CCS",
  "destination":"VIG",
  "departure_date": "2025-07-29",
  "return_date": "2025-08-01"
}


###

POST {{HOST}}/kiu/availability-flights
Content-Type: application/json
x-api-key: {{API_KEY}}
Authorization: Bearer {{TOKEN}}

{
  "adults": 1,
  "children": 0,
  "infants": 0,
  "origin": "CCS",
  "destination": "VIG",
  "departure_date": "2025-07-29",
  "return_date": "2025-08-01",
  "flight_numbers": ["1924", "1925"],
  "carrier": "QL"
} 