@HOST = http://localhost:4050/api
@API_KEY = cfrw9D3kOE9RT6yG
@INT = 87996b9c-b5c8-4943-a204-1a9821eb0914
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjNDQ4NGZlMS1mYTVlLTQzMTUtOWUwYi02MGEyOWU0ODFlYzciLCJpYXQiOjE3NTMxMTMxMjAsImV4cCI6MTc1MzEzMTEyMH0.0Mv5nqkFfUckKD95mb7HEbdXS1NJEHs8cTm-oDwzVsI



POST {{HOST}}/kiu/availability-flights
Content-Type: application/json
x-api-key: {{API_KEY}}
Authorization: Bearer {{TOKEN}}

{
  "adults": 1,
  "children": 0,
  "infants": 0,
  "origin": "CCS",
  "destination": "VIG",
  "departure_date": "2025-07-28",
  "return_date": "2025-07-30"
}


###

POST {{HOST}}/kiu/smart-search
Content-Type: application/json
x-api-key: {{API_KEY}}
Authorization: Bearer {{TOKEN}}

{
  "adults": 1,
  "children": 0,
  "infants": 0,
  "origin": "CCS",
  "destination": "VIG",
  "departure_date": "2025-07-28",
  "return_date": "2025-07-30",
  "flight_numbers": ["1924", "1925"],
  "carrier": "QL"
} 