@HOST = http://e4cc84ssk88o0gk0ggk8ok4o.192.95.40.150.sslip.io/api
@API_KEY = GcE9Rfrw9D37fzN6LkOT6y
@INT = 87996b9c-b5c8-4943-a204-1a9821eb0914


### SEARCHING AVAILABILITY
POST {{HOST}}/kiu/availability-flights?integrationID={{INT}}
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "adults": 1,
  "children": 0,
  "infants": 0,
  "origin": "CCS",
  "destination": "VIG",
  "departure_date": "2025-07-29",
  "return_date": "2025-08-01"
}


### SEARCHING AVAILABILITY
POST {{HOST}}/kiu/smart-search?integrationID={{INT}}
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "adults": 1,
  "children": 0,
  "infants": 0,
  "origin": "CCS",
  "destination": "PMV",
  "departure_date": "2025-07-28",
  "return_date": "2025-07-30",
  "flight_numbers": ["1902", "1907"],
  "carrier": "QL"
} 

### SEARCHING AVAILABILITY


POST {{HOST}}/kiu/smart-booking?integrationID={{INT}}
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "email": "test@vilo.team",
  "phone": "+584121231234",
  "countryCode":"VE",
  "carrier": "QL",
  "passengers": [
    {
      "surname":"GUTIERREZ PEREZ",
      "name":"PEDRO JOSE",
      "gender":"M",
      "foid_type":"ID",
      "document_type":"I",
      "foid_id":"12123123",
      "date_of_birth":"14JAN90",
      "passenger_type_code":"ADT",
      "nationality":"VE",
      "issue_country":"VE",
      "expiration_date":"02APR27"
    }
  ],
  "air_itinerary_information":[
    {
      "order": 1,
      "departure_information": {
        "location_code":"CCS",
        "date":"2025-07-28",
        "time":"1115"
      },
      "arrival_information":{
        "location_code":"VIG"
      },
      "flight_number": 1924,
      "reservation_booking_designator_code": "N",
      "number_in_party": 1,
      "carrier": "QL"
    },
    {
      "order": 2,
      "departure_information": {
        "location_code":"VIG",
        "date":"2025-08-02",
        "time":"1315"
      },
      "arrival_information":{
        "location_code":"CCS"
      },
      "flight_number": 1925,
      "reservation_booking_designator_code": "N",
      "number_in_party": 1,
      "carrier": "QL"
    }
  ]
}


### SEARCHING CALENDAR
POST {{HOST}}/kiu/smart-search-calendar?integrationID={{INT}}
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "adults": 1,
  "children": 0,
  "infants": 0,
  "origin": "CCS",
  "destination": "VIG",
  "departure_date": "2025-07-28", 
  "carrier": "QL"
}